version: "3.9"

services:
  api:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: containers/node/Dockerfile
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    volumes:
      - .:/api
      - api-node-modules:/api/node_modules
    ports:
      - 8080:8080

volumes:
  api-node-modules:
    driver: local
